Feature/theme
seredganyha/bookflow pull request #1
Opened 2024-09-05 08:47 UTC by seredganyha

Описание
Добавил поддержку тем в приложении. Реализовал возможность переключения между базовой(светлой) и темной темой. Потом ThemeService буду юзать в settingsModule.

Получилось поиграться с DI. Использовал InjectionToken вообще вещь, как я раньше без этого жил.

Вопросы/Рассуждения:
- в InjectionToken сразу через factory задаю значения или все-таки лучше это делать в providers куда внедряешь token ?
- Видимо Angular с какой-то версии app component делает standalone. Поэтому все сервисы/токены и т.д на уровне root решил размещать в core папке. Норм идея ?

2024-09-06 06:42 UTC, LuckyWasTaken requested changes

2024-09-06 06:42 UTC, LuckyWasTaken commented on src/app/core/tokens/window-token.ts
> +export const WINDOW = new InjectionToken<Window>('WINDOW', {
Можно брать из https://www.npmjs.com/package/@ng-web-apis/common
Посмотри на их репу, кстати, если не видел

2024-09-06 06:42 UTC, LuckyWasTaken commented on src/app/core/services/theme.service.ts
> +    this.setTheme(newTheme);
Тут получается так, что ты 
а) сделал токен сабжекта текущей темы, который доступен ВЕЗДЕ, но почему-то по логике он должен лежать приватным здесь
б) не реагируешь на стейт реактивно, а по сути меняешь тему руками и просто отправляешь стейт в хранилку (императивненько)

Лучше будет, если ты перенесешь тему бсабжектом сюда и будет у тебя примерно так

```
constructor(...) {
    this.currentTheme$.subscribe(() => this.bodyRef.setAttribute('data-theme', newTheme))
}

toggleTheme() {
    const newTheme = this.currentTheme === Theme.Base ? Theme.Dark : Theme.Base;
    this.setTheme(newTheme);
}
```

2024-09-07 08:41 UTC, seredganyha commented on src/app/core/services/theme.service.ts
> +    this.setTheme(newTheme);
Поправил. Вроде оно.

2024-09-07 08:42 UTC, seredganyha commented on src/app/core/tokens/window-token.ts
> +export const WINDOW = new InjectionToken<Window>('WINDOW', {
Да я видел.

2024-09-11 11:46 UTC, LuckyWasTaken commented on src/app/core/services/theme.service.ts
> +  private readonly themesSource = new BehaviorSubject<Theme[]>(Object.values(Theme))
чет не нашел где оно юзается

2024-09-11 11:52 UTC, seredganyha commented on src/app/core/services/theme.service.ts
> +  private readonly themesSource = new BehaviorSubject<Theme[]>(Object.values(Theme))
Потом вот так юзаю в SettingsModule
    
    {
      provide: CURRENT_THEME,
      useFactory: (themeService: ThemeService) => themeService.currentTheme$,
      deps: [ThemeService]
    },
    {
      provide: THEMES,
      useFactory: (themeService: ThemeService) => themeService.themes$,
      deps: [ThemeService]
    }

2024-09-11 11:52 UTC, seredganyha commented on src/app/core/services/theme.service.ts
> +  private readonly themesSource = new BehaviorSubject<Theme[]>(Object.values(Theme))
в другом PR добавил

2024-09-20 09:34 UTC, merged