Feature/settings
seredganyha/bookflow pull request #2
Opened 2024-09-11 11:33 UTC by seredganyha

2024-09-11 11:53 UTC, LuckyWasTaken requested changes

2024-09-11 11:53 UTC, LuckyWasTaken commented on src/app/settings/settings.component.html
> +    <label for="theme">Текущая тема:</label>
было бы прикольно её кстати из локалстореджа тоже проставлять

2024-09-11 11:53 UTC, LuckyWasTaken commented on src/app/shared/ui/select/select.component.html
> +  <option *ngFor="let option of options" [value]="option">{{ option }}</option>
неплохо было бы trackBy впилить чисто вспомнить/узнать как работает

2024-09-11 11:53 UTC, LuckyWasTaken commented on src/app/shared/ui/select/select.component.ts
> +  imports: [CommonModule],
неплохо узнать/всопмнить про CVA https://habr.com/ru/articles/481424/

2024-09-17 11:07 UTC, seredganyha commented on src/app/settings/settings.component.html
> +    <label for="theme">Текущая тема:</label>
done

2024-09-17 11:07 UTC, seredganyha commented on src/app/shared/ui/select/select.component.html
> +  <option *ngFor="let option of options" [value]="option">{{ option }}</option>
done

2024-09-17 11:07 UTC, seredganyha commented on src/app/shared/ui/select/select.component.ts
> +  imports: [CommonModule],
done

2024-09-17 11:16 UTC, seredganyha commented on src/app/settings/settings.component.html
> +      >
Я реализовал CVA в компоненте, но юзаю также. 
попробовал сделать через ReactiveForms, но изящно не получилось сделать.
Т.е надо в компоненте подписаться на currentTheme. Потом подписаться на  valueChanges и там вызывать onThemeChange как будто императивненько получается.

2024-09-17 11:47 UTC, LuckyWasTaken approved these changes

2024-09-20 09:58 UTC, merged